Fix string truncation warnings
The strncatf macro will cause warnings with latest GCC
if the sizeof the destination buffer is smaller than the temporary buffer.

Resolve by adjusting buffer sizes.

Such as:
git/pktgen-dpdk/app/pktgen-capture.c: In function ‘pktgen_set_capture’:
git/pktgen-dpdk/app/pktgen-log.h:114:3: error: ‘strncat’ output may be truncated copying between 0 and 255 bytes from a string of length 1022 [-Werror=stringop-truncation]
   strncat(dest, _buff, sizeof(dest) - strlen(dest) - 1); \
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
git/pktgen-dpdk/app/pktgen-capture.c:246:7: note: in expansion of macro ‘strncatf’
       strncatf(status, "%d%%", pct);
       ^~~~~~~~
cc1: all warnings being treated as errors

Signed-off-by: Stephen Hemminger <stephen@networkplumber.org>